-- MySQL Script generated by MySQL Workbench
-- Mon Sep 19 12:02:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Exercici 2 Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Exercici 2 Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Exercici 2 Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Exercici 2 Pizzeria` ;

-- -----------------------------------------------------
-- Table `Exercici 2 Pizzeria`.`Adreces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici 2 Pizzeria`.`Adreces` (
  `Adreces_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Adreces_codi_postal` VARCHAR(12) NULL DEFAULT NULL,
  `Adreces_ciutat` VARCHAR(45) NULL DEFAULT NULL,
  `Adreces_provincia` VARCHAR(45) NULL DEFAULT NULL,
  `Adreces_carrer` VARCHAR(45) NULL DEFAULT NULL,
  `Adreces_numero` INT(11) NULL DEFAULT NULL,
  `Adreces_pis` VARCHAR(45) NULL DEFAULT NULL,
  `Adreces_porta` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Adreces_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Exercici 2 Pizzeria`.`Categoria_Pizzes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici 2 Pizzeria`.`Categoria_Pizzes` (
  `Categoria_Pizzes_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Categoria_Pizzes_nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Categoria_Pizzes_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Exercici 2 Pizzeria`.`Comandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici 2 Pizzeria`.`Comandes` (
  `Comandes_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Comandes_timeStamp` DATETIME NULL DEFAULT NULL,
  `Comandes_tipus_entrega` BINARY(2) NULL DEFAULT NULL COMMENT 'tipus comanda:\n0 =  domicili\n1 = botiga\n',
  PRIMARY KEY (`Comandes_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Exercici 2 Pizzeria`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici 2 Pizzeria`.`Clients` (
  `Clients_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Clients_Nom` VARCHAR(45) NULL DEFAULT NULL,
  `Clients_Cognoms` VARCHAR(45) NULL DEFAULT NULL,
  `Adreces_Adreces_id` INT(11) NOT NULL,
  `Clients_telefon` INT(11) NULL DEFAULT NULL,
  `Comandes_Comandes_id` INT(11) NOT NULL,
  PRIMARY KEY (`Clients_id`, `Adreces_Adreces_id`, `Comandes_Comandes_id`),
  INDEX `fk_Clients_Adreces_idx` (`Adreces_Adreces_id` ASC),
  INDEX `fk_Clients_Comandes1_idx` (`Comandes_Comandes_id` ASC),
  CONSTRAINT `fk_Clients_Adreces`
    FOREIGN KEY (`Adreces_Adreces_id`)
    REFERENCES `Exercici 2 Pizzeria`.`Adreces` (`Adreces_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Clients_Comandes1`
    FOREIGN KEY (`Comandes_Comandes_id`)
    REFERENCES `Exercici 2 Pizzeria`.`Comandes` (`Comandes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Exercici 2 Pizzeria`.`Productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici 2 Pizzeria`.`Productes` (
  `Productes_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Productes_nom` VARCHAR(45) NULL DEFAULT NULL,
  `Productes_descripcio` VARCHAR(250) NULL DEFAULT NULL,
  `Productes_imatge_url` VARCHAR(255) NULL DEFAULT NULL,
  `Productes_preu` DECIMAL(2,0) NULL DEFAULT NULL,
  `Productes_categoria_id` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Productes_id`, `Productes_categoria_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Exercici 2 Pizzeria`.`Categoria_Productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici 2 Pizzeria`.`Categoria_Productes` (
  `Productes_Productes_categoria_id` INT(11) NOT NULL,
  `Categoria_Productes_nom` VARCHAR(45) NULL,
  `Categoria_Pizzes_Categoria_Pizzes_id` INT(11) NULL,
  PRIMARY KEY (`Productes_Productes_categoria_id`, `Categoria_Pizzes_Categoria_Pizzes_id`),
  INDEX `fk_Categoria_Productes_Categoria_Pizzes1_idx` (`Categoria_Pizzes_Categoria_Pizzes_id` ASC),
  INDEX `fk_Categoria_Productes_Productes1_idx` (`Productes_Productes_categoria_id` ASC),
  CONSTRAINT `fk_Categoria_Productes_Categoria_Pizzes1`
    FOREIGN KEY (`Categoria_Pizzes_Categoria_Pizzes_id`)
    REFERENCES `Exercici 2 Pizzeria`.`Categoria_Pizzes` (`Categoria_Pizzes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_Productes_Productes1`
    FOREIGN KEY (`Productes_Productes_categoria_id`)
    REFERENCES `Exercici 2 Pizzeria`.`Productes` (`Productes_categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici 2 Pizzeria`.`Botigues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici 2 Pizzeria`.`Botigues` (
  `Botigues_id` INT NOT NULL,
  `Adreces_Adreces_id` INT(11) NOT NULL,
  `Comandes_Comandes_id` INT(11) NOT NULL,
  PRIMARY KEY (`Botigues_id`, `Adreces_Adreces_id`, `Comandes_Comandes_id`),
  INDEX `fk_Botigues_Adreces1_idx` (`Adreces_Adreces_id` ASC),
  INDEX `fk_Botigues_Comandes1_idx` (`Comandes_Comandes_id` ASC),
  CONSTRAINT `fk_Botigues_Adreces1`
    FOREIGN KEY (`Adreces_Adreces_id`)
    REFERENCES `Exercici 2 Pizzeria`.`Adreces` (`Adreces_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Botigues_Comandes1`
    FOREIGN KEY (`Comandes_Comandes_id`)
    REFERENCES `Exercici 2 Pizzeria`.`Comandes` (`Comandes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici 2 Pizzeria`.`Detall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici 2 Pizzeria`.`Detall` (
  `Detall_id` INT NOT NULL AUTO_INCREMENT,
  `Productes_Productes_id` INT(11) NOT NULL,
  `Detall_quantitat` INT NULL,
  `Comandes_Comandes_id` INT(11) NOT NULL,
  PRIMARY KEY (`Detall_id`, `Productes_Productes_id`, `Comandes_Comandes_id`),
  INDEX `fk_Detall_Comandes1_idx` (`Comandes_Comandes_id` ASC),
  CONSTRAINT `fk_Detall_Productes1`
    FOREIGN KEY (`Productes_Productes_id`)
    REFERENCES `Exercici 2 Pizzeria`.`Productes` (`Productes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detall_Comandes1`
    FOREIGN KEY (`Comandes_Comandes_id`)
    REFERENCES `Exercici 2 Pizzeria`.`Comandes` (`Comandes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici 2 Pizzeria`.`Empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici 2 Pizzeria`.`Empleats` (
  `Empleats_id` INT NOT NULL,
  `Empleats_nom` VARCHAR(45) NULL,
  `Empleats_cognoms` VARCHAR(45) NULL,
  `Empleats_NIF` VARCHAR(45) NULL,
  `Empleats_telefon` INT NULL,
  `Botigues_Botigues_id` INT NOT NULL,
  PRIMARY KEY (`Empleats_id`, `Botigues_Botigues_id`),
  INDEX `fk_Empleats_Botigues1_idx` (`Botigues_Botigues_id` ASC),
  CONSTRAINT `fk_Empleats_Botigues1`
    FOREIGN KEY (`Botigues_Botigues_id`)
    REFERENCES `Exercici 2 Pizzeria`.`Botigues` (`Botigues_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici 2 Pizzeria`.`Comandes_domicili`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici 2 Pizzeria`.`Comandes_domicili` (
  `Comandes_Comandes_id` INT(11) NOT NULL,
  `Empleats_Empleats_id` INT NOT NULL,
  `Comandes_domicili_data/hora` DATETIME NULL,
  PRIMARY KEY (`Comandes_Comandes_id`, `Empleats_Empleats_id`),
  INDEX `fk_Comandes_domicili_Empleats1_idx` (`Empleats_Empleats_id` ASC),
  CONSTRAINT `fk_Comandes_domicili_Comandes1`
    FOREIGN KEY (`Comandes_Comandes_id`)
    REFERENCES `Exercici 2 Pizzeria`.`Comandes` (`Comandes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comandes_domicili_Empleats1`
    FOREIGN KEY (`Empleats_Empleats_id`)
    REFERENCES `Exercici 2 Pizzeria`.`Empleats` (`Empleats_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
